name: CI
on: push
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test:unit
      - name: Install playwright install --with-deps
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
      - name: Get installed Playwright version
        id: playwright-version
          retention-days: 30
        run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').dependencies['@playwright/test'].version)")" >> $GITHUB_ENV
        if: steps.playwright-cache.outputs.cache-hit != 'true'
      - name: Cache playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
            path: |
            ~/.cache/ms-playwright
            key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "Building the project" && exit 0
